language: node_js
node_js:
  - 10
  - stable
git:
  depth: 1
branches:
  only:
    - master
after_success:
  - "npm run coveralls"
deploy:
  on:
    branch: master
    tags: true
  provider: npm
  email: umutozel@gmail.com
  api_key:
    secure: 