# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    cd src
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    cd src
    npm t
  displayName: 'npm run tests and coverage'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: Cobertura
    testResultsFiles: '$(System.DefaultWorkingDirectory)/src/coverage/cobertura-coverage.xml'

- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/src/coverage/cobertura-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/src/coverage/lcov-report'